Suspended now counts as failed
segevm/Classifying-US-Kickstarter-Projects pull request #1
Opened 2019-11-26 08:08 UTC by efarka

2019-11-27 23:30 UTC, segevm requested changes

2019-11-27 23:30 UTC, segevm commented on final project cleaning.Rmd
> +projects$deadline <- strptime(projects$deadline, "%Y-%m-%d")
Don't we want both these variables to be in the same date format for consistency in calculations? I feel like we should just remove the %H:%M:%S from projects$launched

2019-11-27 23:30 UTC, segevm commented on final project cleaning.Rmd
> +projects$state2[projects$state=="suspended"] <- 0
Missing the "live" and "undefined" states

Also, don't we want to factor the projects$state2?

2019-11-28 00:01 UTC, efarka commented on final project cleaning.Rmd
> +projects$deadline <- strptime(projects$deadline, "%Y-%m-%d")
Sure!

2019-11-28 00:05 UTC, efarka commented on final project cleaning.Rmd
> +projects$state2[projects$state=="suspended"] <- 0
Live and undefined are removed in the line below this.  They don't really cleanly into successful or failed so it makes more sense to not analyze them.  
I kinda coded it in a weird way lol but the state2 ends up replacing the state column later on. I drop the original state column and rename state2 to state.

2019-11-30 18:19 UTC, closed without merging